@php($fieldClass = 'w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-green-500 focus:ring-2 focus:ring-green-200')
<div class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2"><label class="mb-1 block text-sm font-medium text-gray-700">Nama Metode *</label><input name="name" required maxlength="150" value="{{ old('name', $cfMethod?->name) }}" class="{{ $fieldClass }}">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Versi *</label><input name="version" required maxlength="30" value="{{ old('version', $cfMethod?->version) }}" class="{{ $fieldClass }}">@error('version')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Status</label><label class="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $cfMethod?->is_active ?? true))> Aktif</label></div>
    <div class="sm:col-span-2"><label class="mb-1 block text-sm font-medium text-gray-700">Deskripsi</label><textarea name="description" rows="3" class="{{ $fieldClass }}">{{ old('description', $cfMethod?->description) }}</textarea></div>
    <div class="sm:col-span-2"><label class="mb-1 block text-sm font-medium text-gray-700">Template Pertanyaan Elicitation *</label><textarea name="elicitation_question_template" required rows="2" class="{{ $fieldClass }}">{{ old('elicitation_question_template', $cfMethod?->elicitation_question_template) }}</textarea><p class="mt-1 text-xs text-gray-500">Gunakan placeholder {gejala} dan {penyakit} bila pertanyaan perlu menampilkan relasi aturan.</p></div>
    <div class="sm:col-span-2"><label class="mb-1 block text-sm font-medium text-gray-700">Skala (satu baris per tingkat: term|cf) *</label><textarea name="scale_text" required rows="8" class="{{ $fieldClass }}">{{ old('scale_text', collect($cfMethod?->scaleOptions() ?? [])->map(fn ($option) => $option['term'].'|'.$option['cf'])->implode("\n")) }}</textarea><p class="mt-1 text-xs text-gray-500">Contoh: Hampir Pasti|0.8. UI menampilkan tabel readable; JSON tidak ditampilkan.</p></div>
    <div class="sm:col-span-2"><p class="text-sm font-semibold text-[#173b29]">Referensi Metodologi CF</p></div>
    <div class="sm:col-span-2"><label class="mb-1 block text-sm font-medium text-gray-700">Judul</label><input name="reference_title" maxlength="255" value="{{ old('reference_title', $cfMethod?->reference_title) }}" class="{{ $fieldClass }}"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Penulis</label><input name="reference_authors" maxlength="255" value="{{ old('reference_authors', $cfMethod?->reference_authors) }}" class="{{ $fieldClass }}"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Tahun</label><input type="number" name="reference_year" min="1800" max="{{ date('Y') }}" value="{{ old('reference_year', $cfMethod?->reference_year) }}" class="{{ $fieldClass }}"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">DOI</label><input name="reference_doi" maxlength="255" value="{{ old('reference_doi', $cfMethod?->reference_doi) }}" class="{{ $fieldClass }}"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">URL</label><input type="url" name="reference_url" maxlength="500" value="{{ old('reference_url', $cfMethod?->reference_url) }}" class="{{ $fieldClass }}"></div>
</div>
