// DEV MOCK ONLY: these records represent case locations in West Java.
// Replace this source with the read-only M2 case contract when it is available.
export const mockCases = [
    {
        case_id: 1,
        case_code: 'KAS-2026-001',
        latitude: -6.9147,
        longitude: 107.6098,
        kelompok_tani: { id: 1, nama: 'Poktan Mekar Jaya' },
        komoditas: { id: 1, kode: 'KP-045', nama: 'Karet' },
        penyakit: { id: 1, nama: 'Jamur Akar Putih' },
        popt: { id: 1, nama: 'Dedi Suherman' },
        wilayah: {
            kode_kabupaten: '3273',
            kabupaten: 'KOTA BANDUNG',
            kode_kecamatan: '3273010',
            kecamatan: 'Sukasari',
        },
        status: 'in_progress',
        last_note: 'Penanganan sedang dilaksanakan.',
        last_status_at: '2026-08-15T10:00:00+07:00',
        status_history: [
            { status: 'assigned', note: 'POPT ditugaskan.', changed_at: '2026-08-10T08:00:00+07:00' },
            { status: 'under_review', note: 'Kasus sedang direview.', changed_at: '2026-08-11T09:30:00+07:00' },
            { status: 'in_progress', note: 'Penanganan sedang dilakukan.', changed_at: '2026-08-15T10:00:00+07:00' },
        ],
    },
    {
        case_id: 2,
        case_code: 'KAS-2026-002',
        latitude: -6.595,
        longitude: 106.8167,
        kelompok_tani: { id: 2, nama: 'Poktan Sinar Tani' },
        komoditas: { id: 2, kode: 'KP-012', nama: 'Kopi Arabika' },
        penyakit: { id: 2, nama: 'Karat Daun' },
        popt: { id: 2, nama: 'Rina Kurniasih' },
        wilayah: {
            kode_kabupaten: '3201',
            kabupaten: 'KABUPATEN BOGOR',
            kode_kecamatan: '3201010',
            kecamatan: 'Cibinong',
        },
        status: 'assigned',
        last_note: 'Kasus ditugaskan untuk verifikasi lapangan.',
        last_status_at: '2026-08-14T09:30:00+07:00',
        status_history: [
            { status: 'assigned', note: 'POPT ditugaskan untuk verifikasi lapangan.', changed_at: '2026-08-14T09:30:00+07:00' },
        ],
    },
    {
        case_id: 3,
        case_code: 'KAS-2026-003',
        latitude: -6.8208,
        longitude: 107.1428,
        kelompok_tani: { id: 3, nama: 'Poktan Harapan Mulya' },
        komoditas: { id: 3, kode: 'KP-021', nama: 'Teh' },
        penyakit: { id: 3, nama: 'Helopeltis' },
        popt: { id: 3, nama: 'Agus Ramdani' },
        wilayah: {
            kode_kabupaten: '3203',
            kabupaten: 'KABUPATEN CIANJUR',
            kode_kecamatan: '3203010',
            kecamatan: 'Cianjur',
        },
        status: 'under_review',
        last_note: 'Hasil identifikasi sedang ditinjau.',
        last_status_at: '2026-08-13T14:15:00+07:00',
        status_history: [
            { status: 'assigned', note: 'Kasus diteruskan kepada POPT.', changed_at: '2026-08-12T08:45:00+07:00' },
            { status: 'under_review', note: 'Hasil identifikasi sedang ditinjau.', changed_at: '2026-08-13T14:15:00+07:00' },
        ],
    },
    {
        case_id: 4,
        case_code: 'KAS-2026-004',
        latitude: -7.2167,
        longitude: 107.9,
        kelompok_tani: { id: 4, nama: 'Poktan Tani Sejahtera' },
        komoditas: { id: 4, kode: 'KP-033', nama: 'Tembakau' },
        penyakit: { id: 4, nama: 'Lanas' },
        popt: { id: 4, nama: 'Yayan Hidayat' },
        wilayah: {
            kode_kabupaten: '3205',
            kabupaten: 'KABUPATEN GARUT',
            kode_kecamatan: '3205010',
            kecamatan: 'Garut Kota',
        },
        status: 'postponed',
        last_note: 'Kunjungan lapangan ditunda karena cuaca.',
        last_status_at: '2026-08-12T11:45:00+07:00',
        status_history: [
            { status: 'assigned', note: 'POPT ditugaskan untuk kunjungan.', changed_at: '2026-08-11T09:00:00+07:00' },
            { status: 'postponed', note: 'Kunjungan lapangan ditunda karena cuaca.', changed_at: '2026-08-12T11:45:00+07:00' },
        ],
    },
    {
        case_id: 5,
        case_code: 'KAS-2026-005',
        latitude: -6.9277,
        longitude: 106.93,
        kelompok_tani: { id: 5, nama: 'Poktan Subur Makmur' },
        komoditas: { id: 5, kode: 'KP-008', nama: 'Kelapa' },
        penyakit: { id: 5, nama: 'Kumbang Janur' },
        popt: { id: 5, nama: 'Siti Maryam' },
        wilayah: {
            kode_kabupaten: '3202',
            kabupaten: 'KABUPATEN SUKABUMI',
            kode_kecamatan: '3202010',
            kecamatan: 'Cisaat',
        },
        status: 'ready_for_execution',
        last_note: 'Rencana tindakan siap dijalankan.',
        last_status_at: '2026-08-11T08:20:00+07:00',
        status_history: [
            { status: 'assigned', note: 'POPT ditugaskan untuk penanganan.', changed_at: '2026-08-09T08:30:00+07:00' },
            { status: 'under_review', note: 'Rencana tindakan sedang disusun.', changed_at: '2026-08-10T13:10:00+07:00' },
            { status: 'ready_for_execution', note: 'Rencana tindakan siap dijalankan.', changed_at: '2026-08-11T08:20:00+07:00' },
        ],
    },
    {
        case_id: 6,
        case_code: 'KAS-2026-006',
        latitude: -7.3274,
        longitude: 108.2207,
        kelompok_tani: { id: 6, nama: 'Poktan Mandiri' },
        komoditas: { id: 6, kode: 'KP-016', nama: 'Kakao' },
        penyakit: { id: 6, nama: 'Penggerek Buah Kakao' },
        popt: { id: 6, nama: 'Bambang Irawan' },
        wilayah: {
            kode_kabupaten: '3206',
            kabupaten: 'KABUPATEN TASIKMALAYA',
            kode_kecamatan: '3206010',
            kecamatan: 'Tawang',
        },
        status: 'completed',
        last_note: 'Penanganan dan pemantauan telah selesai.',
        last_status_at: '2026-08-10T16:00:00+07:00',
        status_history: [
            { status: 'assigned', note: 'POPT ditugaskan.', changed_at: '2026-08-06T08:00:00+07:00' },
            { status: 'under_review', note: 'Hasil identifikasi direview.', changed_at: '2026-08-07T10:15:00+07:00' },
            { status: 'in_progress', note: 'Penanganan dilaksanakan.', changed_at: '2026-08-08T09:20:00+07:00' },
            { status: 'completed', note: 'Penanganan dan pemantauan telah selesai.', changed_at: '2026-08-10T16:00:00+07:00' },
        ],
    },
    {
        case_id: 7,
        case_code: 'KAS-2026-007',
        latitude: -6.571,
        longitude: 107.7587,
        kelompok_tani: { id: 7, nama: 'Poktan Bina Usaha' },
        komoditas: { id: 7, kode: 'KP-004', nama: 'Kelapa Sawit' },
        penyakit: { id: 7, nama: 'Busuk Pangkal Batang' },
        popt: { id: 7, nama: 'Nurul Aini' },
        wilayah: {
            kode_kabupaten: '3213',
            kabupaten: 'KABUPATEN SUBANG',
            kode_kecamatan: '3213010',
            kecamatan: 'Subang',
        },
        status: 'assigned',
        last_note: 'Menunggu jadwal pemeriksaan awal.',
        last_status_at: '2026-08-09T10:10:00+07:00',
        status_history: [
            { status: 'assigned', note: 'Menunggu jadwal pemeriksaan awal.', changed_at: '2026-08-09T10:10:00+07:00' },
        ],
    },
    {
        case_id: 8,
        case_code: 'KAS-2026-008',
        latitude: -6.732,
        longitude: 108.5523,
        kelompok_tani: { id: 8, nama: 'Poktan Sumber Rezeki' },
        komoditas: { id: 8, kode: 'KP-027', nama: 'Tebu' },
        penyakit: { id: 8, nama: 'Penggerek Batang' },
        popt: { id: 8, nama: 'Taufik Heryana' },
        wilayah: {
            kode_kabupaten: '3209',
            kabupaten: 'KABUPATEN CIREBON',
            kode_kecamatan: '3209010',
            kecamatan: 'Sumber',
        },
        status: 'in_progress',
        last_note: 'Aplikasi pengendalian sedang berlangsung.',
        last_status_at: '2026-08-08T13:25:00+07:00',
        status_history: [
            { status: 'assigned', note: 'POPT ditugaskan untuk penanganan.', changed_at: '2026-08-06T08:40:00+07:00' },
            { status: 'ready_for_execution', note: 'Rencana pengendalian siap dijalankan.', changed_at: '2026-08-07T11:00:00+07:00' },
            { status: 'in_progress', note: 'Aplikasi pengendalian sedang berlangsung.', changed_at: '2026-08-08T13:25:00+07:00' },
        ],
    },
    {
        case_id: 9,
        case_code: 'KAS-2026-009',
        latitude: -6.9833,
        longitude: 108.4833,
        kelompok_tani: { id: 9, nama: 'Poktan Karya Bakti' },
        komoditas: { id: 9, kode: 'KP-013', nama: 'Kopi Robusta' },
        penyakit: { id: 9, nama: 'Bercak Daun' },
        popt: { id: 9, nama: 'Mila Rosdiana' },
        wilayah: {
            kode_kabupaten: '3208',
            kabupaten: 'KABUPATEN KUNINGAN',
            kode_kecamatan: '3208010',
            kecamatan: 'Kuningan',
        },
        status: 'under_review',
        last_note: 'Dokumentasi kasus sedang diperiksa.',
        last_status_at: '2026-08-07T15:40:00+07:00',
        status_history: [
            { status: 'assigned', note: 'Kasus diterima untuk pemeriksaan.', changed_at: '2026-08-06T09:15:00+07:00' },
            { status: 'under_review', note: 'Dokumentasi kasus sedang diperiksa.', changed_at: '2026-08-07T15:40:00+07:00' },
        ],
    },
    {
        case_id: 10,
        case_code: 'KAS-2026-010',
        latitude: -6.5705,
        longitude: 106.7469,
        kelompok_tani: { id: 10, nama: 'Poktan Wargi Saluyu' },
        komoditas: { id: 10, kode: 'KP-046', nama: 'Karet' },
        penyakit: { id: 10, nama: 'Mouldy Rot' },
        popt: { id: 10, nama: 'Eko Prasetyo' },
        wilayah: {
            kode_kabupaten: '3201',
            kabupaten: 'KABUPATEN BOGOR',
            kode_kecamatan: '3201020',
            kecamatan: 'Dramaga',
        },
        status: 'completed',
        last_note: 'Kasus selesai setelah evaluasi akhir.',
        last_status_at: '2026-08-06T09:05:00+07:00',
        status_history: [
            { status: 'assigned', note: 'POPT ditugaskan.', changed_at: '2026-08-03T08:15:00+07:00' },
            { status: 'under_review', note: 'Hasil pemeriksaan direview.', changed_at: '2026-08-04T10:30:00+07:00' },
            { status: 'completed', note: 'Kasus selesai setelah evaluasi akhir.', changed_at: '2026-08-06T09:05:00+07:00' },
        ],
    },
];
