@extends('layouts.app')

@section('title', 'Detail Penugasan')

@php
    $statusLabels = ['diterima' => 'Diterima', 'ditugaskan' => 'Ditugaskan', 'sedang_direview' => 'Sedang Direview', 'ditunda' => 'Ditunda', 'siap_dieksekusi' => 'Siap Dieksekusi', 'dalam_pelaksanaan' => 'Dalam Pelaksanaan', 'selesai' => 'Selesai'];
    $allowedStatuses = config('kasus.transitions.'.$kasus->current_status, []);
@endphp

@section('content')
<div class="mx-auto max-w-5xl space-y-6"><div><a href="{{ route('popt.penugasan') }}" class="text-sm text-[#176b45]">← Penugasan saya</a><div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="text-2xl font-bold text-[#173b29]">{{ $kasus->kasus_code }}</h1><span class="rounded-full bg-[#eef6f1] px-3 py-1.5 text-sm font-semibold text-[#176b45]">{{ $statusLabels[$kasus->current_status] ?? $kasus->current_status }}</span></div></div>
@if(session('success'))<div class="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-5 lg:grid-cols-2"><section class="rounded-xl border border-[#e6eee8] bg-white p-5"><h2 class="font-bold text-[#173b29]">Detail kasus</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-gray-500">Pemohon</dt><dd>{{ $kasus->permohonan?->creator?->name ?? '-' }}</dd></div><div><dt class="text-gray-500">Kelompok tani</dt><dd>{{ $kasus->permohonan?->kelompok_tani_name_snapshot ?? '-' }}</dd></div><div><dt class="text-gray-500">Komoditas</dt><dd>{{ $kasus->komoditas_name_snapshot ?: '-' }}</dd></div><div><dt class="text-gray-500">Penyakit</dt><dd>{{ $kasus->penyakit_name_snapshot ?: '-' }}</dd></div><div><dt class="text-gray-500">Koordinat kasus</dt><dd>{{ $kasus->latitude_kasus ?? '-' }}, {{ $kasus->longitude_kasus ?? '-' }}</dd></div></dl></section><section class="rounded-xl border border-[#e6eee8] bg-white p-5"><h2 class="font-bold text-[#173b29]">Perbarui progres</h2>@if($allowedStatuses)<form method="POST" action="{{ route('popt.penugasan.status', $kasus->id) }}" class="mt-4 space-y-3">@csrf<label class="block text-sm font-medium text-gray-700">Status berikutnya<select name="status" required class="mt-1 w-full rounded-lg border-gray-300 text-sm"><option value="">Pilih status</option>@foreach($allowedStatuses as $status)<option value="{{ $status }}">{{ $statusLabels[$status] ?? $status }}</option>@endforeach</select></label><label class="block text-sm font-medium text-gray-700">Catatan audit/progres<textarea name="catatan" rows="4" class="mt-1 w-full rounded-lg border-gray-300 text-sm" placeholder="Catatan pemeriksaan atau tindakan"></textarea></label><button class="w-full rounded-lg bg-[#176b45] px-4 py-2.5 text-sm font-semibold text-white">Simpan Progres</button></form>@else<p class="mt-4 text-sm text-gray-500">Kasus sudah selesai. Riwayat, diagnosis, lokasi, dan detail penanganan tetap dapat dibaca.</p>@endif</section></div>
<section class="rounded-xl border border-[#e6eee8] bg-white p-5"><h2 class="font-bold text-[#173b29]">Riwayat penanganan</h2><ol class="mt-4 space-y-3">@forelse($kasus->riwayatStatus as $riwayat)<li class="border-l-2 border-[#cfe2d5] pl-3 text-sm"><strong>{{ $statusLabels[$riwayat->status] ?? $riwayat->status }}</strong><span class="text-gray-500"> · {{ $riwayat->created_at?->format('d-m-Y H:i') }}</span><p class="text-gray-600">{{ $riwayat->catatan ?: 'Tanpa catatan' }}</p></li>@empty<li class="text-sm text-gray-500">Belum ada riwayat.</li>@endforelse</ol></section></div>
@endsection
