@extends('layouts.app')

@section('title', 'Monitoring Kasus')

@php($statusLabels = ['diterima' => 'Diterima — Menunggu Penugasan', 'ditugaskan' => 'Ditugaskan', 'sedang_direview' => 'Sedang Direview', 'ditunda' => 'Ditunda', 'siap_dieksekusi' => 'Siap Dieksekusi', 'dalam_pelaksanaan' => 'Dalam Pelaksanaan', 'selesai' => 'Selesai'])

@section('content')
<div class="space-y-6"><div class="flex items-end justify-between"><div><h1 class="text-2xl font-bold text-[#173b29]">Monitoring Kasus</h1><p class="mt-1 text-sm text-[#77847c]">Pantau kasus dan lakukan penugasan POPT.</p></div><a href="{{ route('operator.permohonan') }}" class="rounded-lg border border-[#cfe2d5] px-4 py-2 text-sm font-semibold text-[#176b45]">Permohonan Masuk</a></div>
<form method="GET" class="flex gap-3 rounded-xl border border-[#e6eee8] bg-white p-4"><select name="status" class="rounded-lg border-gray-300 text-sm"><option value="">Semua status</option>@foreach($statusLabels as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-[#176b45] px-4 py-2 text-sm font-semibold text-white">Filter</button></form>
<div class="overflow-hidden rounded-xl border border-[#e6eee8] bg-white"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Kasus</th><th class="px-4 py-3 text-left">Komoditas / Penyakit</th><th class="px-4 py-3 text-left">POPT</th><th class="px-4 py-3 text-left">Status</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($kasus as $item)<tr><td class="px-4 py-3 font-mono text-xs">{{ $item->kasus_code }}</td><td class="px-4 py-3">{{ $item->komoditas_name_snapshot ?: '-' }}<br><span class="text-xs text-gray-500">{{ $item->penyakit_name_snapshot ?: '-' }}</span></td><td class="px-4 py-3">{{ $item->penugasanAktif?->popt?->name ?? 'Belum ditugaskan' }}</td><td class="px-4 py-3"><span class="rounded-full bg-[#eef6f1] px-2.5 py-1 text-xs font-semibold text-[#176b45]">{{ $statusLabels[$item->current_status] ?? $item->current_status }}</span></td><td class="px-4 py-3 text-right"><a href="{{ route('operator.kasus.show', $item->id) }}" class="font-semibold text-[#176b45]">Detail</a></td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-gray-500">Belum ada kasus.</td></tr>@endforelse</tbody></table></div><div class="border-t border-gray-100 px-4 py-3">{{ $kasus->withQueryString()->links() }}</div></div></div>
@endsection
