@extends('layouts.app')

@section('title', 'Detail Kasus')

@php($statusLabels = ['diterima' => 'Diterima — Menunggu Penugasan', 'ditugaskan' => 'Ditugaskan', 'sedang_direview' => 'Sedang Direview', 'ditunda' => 'Ditunda', 'siap_dieksekusi' => 'Siap Dieksekusi', 'dalam_pelaksanaan' => 'Dalam Pelaksanaan', 'selesai' => 'Selesai'])

@section('content')
<div class="mx-auto max-w-5xl space-y-6"><div><a href="{{ route('operator.kasus.index') }}" class="text-sm text-[#176b45]">← Monitoring kasus</a><div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="text-2xl font-bold text-[#173b29]">{{ $kasus->kasus_code }}</h1><span class="rounded-full bg-[#eef6f1] px-3 py-1.5 text-sm font-semibold text-[#176b45]">{{ $statusLabels[$kasus->current_status] ?? $kasus->current_status }}</span></div></div>
@if(session('success'))<div class="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('success') }}</div>@endif
<section class="grid gap-5 rounded-xl border border-[#e6eee8] bg-white p-5 sm:grid-cols-2"><div><h2 class="font-bold text-[#173b29]">Ringkasan</h2><dl class="mt-4 space-y-2 text-sm"><div><dt class="text-gray-500">Komoditas</dt><dd>{{ $kasus->komoditas_name_snapshot ?: '-' }}</dd></div><div><dt class="text-gray-500">Penyakit</dt><dd>{{ $kasus->penyakit_name_snapshot ?: '-' }}</dd></div><div><dt class="text-gray-500">Lokasi</dt><dd>{{ $kasus->latitude_kasus ?? '-' }}, {{ $kasus->longitude_kasus ?? '-' }}</dd></div></dl></div><div><h2 class="font-bold text-[#173b29]">Penugasan POPT</h2><p class="mt-4 text-sm">{{ $kasus->penugasanAktif?->popt?->name ?? 'Belum ditugaskan' }}</p>@if($kasus->current_status !== 'selesai')<form method="POST" action="{{ route('operator.kasus.assign', $kasus->id) }}" class="mt-4 space-y-2">@csrf<select name="popt_id" required class="w-full rounded-lg border-gray-300 text-sm"><option value="">Pilih POPT aktif</option>@foreach($popts as $popt)<option value="{{ $popt->id }}" @selected($kasus->penugasanAktif?->popt_id === $popt->id)>{{ $popt->name }}</option>@endforeach</select><textarea name="catatan" rows="2" class="w-full rounded-lg border-gray-300 text-sm" placeholder="Catatan penugasan (opsional)"></textarea><button class="w-full rounded-lg bg-[#176b45] px-4 py-2 text-sm font-semibold text-white">Simpan Penugasan</button></form>@endif</div></section>
<section class="rounded-xl border border-[#e6eee8] bg-white p-5"><h2 class="font-bold text-[#173b29]">Riwayat progres</h2><ol class="mt-4 space-y-3">@forelse($kasus->riwayatStatus as $riwayat)<li class="border-l-2 border-[#cfe2d5] pl-3 text-sm"><strong>{{ $statusLabels[$riwayat->status] ?? $riwayat->status }}</strong><span class="text-gray-500"> · {{ $riwayat->created_at?->format('d-m-Y H:i') }}</span><p class="text-gray-600">{{ $riwayat->catatan ?: 'Tanpa catatan' }}</p></li>@empty<li class="text-sm text-gray-500">Belum ada riwayat.</li>@endforelse</ol></section></div>
@endsection
